#!/usr/bin/env perl

=head1 NAME

  Kalk - execute a command line calculator written in Perl

=head1 SYNOPSYS

  $ kalk [-h] [-v] expression

=head1 DESCRIPTION

  This script reads command arguments as one algebraic expresseion,
  calculates it, and prints the answer with the input expression.
  Numbers can contain either commas or spaces in themselves
  like 1,017,283.

=head1 OPTIONS

  -h  Print help
  -v  Print script name with its version

=head1 EXAMPLES

  $ perldoc kalk
  $ kalk -h
  $ kalk -v
  $ kalk 9+5
  $ kalk 2**8
  $ kalk '(57+139)*1.05/2'
  $ kalk sqrt 3
  $ kalk 1,017,283 + 1,327,720

=head1 AUTHOR

  Coded by Kohji OKAMURA, Ph.D

=head1 HISTORY

  Apr 14, 2005  The initial version as calc.pl
  Apr 18, 2005  Minor modification
  May 31, 2007  POD and error message are added
  Jan 23, 2009  Modified a little (use warnings etc.)
  Mar 17, 2010  Accept commas
  Oct 13, 2010  Minor modification
  Jul 31, 2012  Print original input expression
  Apr 25, 2016  Renamed as Kalk from calc; released as Kalk ver. 1.0

=cut


my $VERSION = '1.0';

use warnings;
use strict;
use English;

unless (scalar @ARGV)                                     { exec "perldoc $0" }
	# check the number of arguments by scalar()
if ($ARGV[0] eq '-h')                                     { exec "perldoc $0" }
if ($ARGV[0] eq '-v') { print "Kalk ($0) ver. $VERSION\n"; exit }

my $expr = "@ARGV";
$expr =~ tr/ ,//d;	# remove spaces and commas
print "@ARGV", ' = ', eval $expr, "\n";
exit
